### ISSUE TITLE
What is the difference between polybox and piku?

### ISSUE THREAD

**Issue by n3storm** [mardix/sailor#1]
I am planning to use one of them.
What made you fork piku?

Thanks in advance

**Comment by n3storm** [comment]
maybe php support?

**Comment by mardix** [comment]
Sorry for the delayed responses. Just saw it. :) 

First, Polybox is a fork of Piku. Thanks to them. 

Some the differences:
- Focus mainly on deploying application to VPS 
- It uses a manifest `polybox.yml` that contains the configuration. Also more rich, as you can set more options
- Allow the deployment of multiple sites from the same repo. Just add a new app in the `polybox.yml`
- Has metrics for the apps
- Simpler installation
- Core languages: Python, Node, Static site + PHP
- Doesn't have a client. But use SSH similar to Piku
- Environment variables are in the `polybox.yml`
- Support Python 3.8 and Ubuntu 20.04
